#config.gocd.yaml
environments:
  dev:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - hello-django
pipelines:
  hello-django:
    group: django-app-group
    materials:
      mygit:  # this is the name of material
        git: https://github.com/davified/hello-django.git
    stages:
      - build: # name of stage
          jobs:
            helloGocd: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-cl"
                    - "echo"
                    - "hello gocd"
            runUnitTests: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-cl"
                    - "python"
                    - "manage.py"
                    - "test"
